"""added new field

Revision ID: 54ac83fd4701
Revises: a695d0e7eea8
Create Date: 2026-04-29 18:05:05.670475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ac83fd4701'
down_revision: Union[str, Sequence[str], None] = 'a695d0e7eea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('entered_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'entered_time')
    # ### end Alembic commands ###
